AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: DynamoDB Table Deployment using AWS SAM

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:

  ProductCatalogTable:
    Type: AWS::DynamoDB::Table
    Properties:

      TableName: !Sub product-catalog-${Environment}

      BillingMode: PAY_PER_REQUEST

      TableClass: STANDARD_INFREQUENT_ACCESS

      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S

        - AttributeName: category
          AttributeType: S

        - AttributeName: supplier
          AttributeType: S

      KeySchema:
        - AttributeName: productId
          KeyType: HASH

      GlobalSecondaryIndexes:

        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: SupplierIndex
          KeySchema:
            - AttributeName: supplier
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:

  TableName:
    Value: !Ref ProductCatalogTable

  TableArn:
    Value: !GetAtt ProductCatalogTable.Arn
