template-file-path: foundation/foundation.yaml
stack-name: bem16-foundation
region: eu-west-1
capabilities:
  - CAPABILITY_IAM
  - CAPABILITY_NAMED_IAM
parameters:
  ProjectName: bem16
  GitHubOrg: nlenjibi
  GitHubRepo: dynamodb
  DevArtifactsBucketName: bem-sam-dev-artifacts
  ProdArtifactsBucketName: bem-sam-prod-artifacts
tags:
  Project: bem16
  ManagedBy: CloudFormation-GitSync
