name: Deploy Prod

on:
  push:
    branches:
      - main

concurrency:
  group: prod-deployment
  cancel-in-progress: false

jobs:
  deploy:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate
        run: sam validate

      - name: Build
        run: sam build

      - name: Deploy
        run: sam deploy --config-env prod
