name: Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2


      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build
        run: sam build

      - name: Deploy
        run: |
          sam deploy \
          --stack-name dynamodb-dev \
          --parameter-overrides Environment=dev \
          --s3-bucket sam-dev-artifacts \
          --capabilities CAPABILITY_IAM \
          --no-confirm-changeset